export const ADD_ROLE = 'ADD_ROLE';
export const DELETE_ROLE = 'DELETE_ROLE';

export const SEARCH_ROLE = 'SEARCH_ROLE';
export const ADD_PERMISSION = 'ADD_PERMISSION';
export const SEARCH_PERMISSIONS = 'SEARCH_PERMISSIONS';
export const DELETE_PERMISSION = 'DELETE_PERMISSION';
