
export const UPDATE_RESIUM_MODE = 'resium/UPDATE_RESIUM_MODE';
export const NODE_SELECTED = 'resium/NODE_SELECTED';
export const ON_RIGHT_MENU_OPTION_CLICK = 'resium/ON_RIGHT_MENU_OPTION_CLICK';
export const ELEMENTS_SELECTED = 'resium/ELEMENTS_SELECTED';

